### ISSUE TITLE
When trying to access `PrivateRoute`, move user to login screens, but redirect back to the initial destination as soon as he's authorized

### ISSUE THREAD

**Issue by Ugzuzg** [razam-ecosystem/task-tracker#24]

**Comment by alesiaviktorchyk** [comment]
Verified. Works as expected.
![screenshot-nimbus-capture-2020 07 26-19_59_59](https://user-images.githubusercontent.com/45420854/88484887-bb169300-cf7a-11ea-845c-8a8b73c6cecd.gif)
