### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#26]
1. Remove icons of viber, watsapp, telegram; 
2. Change the titles' colour; 
3. Correct indents;
4. Add tooltips for all social network account of the company, see example Instagram: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=411%3A0; 
5. Style language drop-down component. 

See deatils on design: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=1%3A1646

**Comment by alesiaviktorchyk** [comment]
Verified.
