### ISSUE TITLE
Peplace Icon "Сube" On Landing

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#27]
<img width="529" alt="image" src="https://user-images.githubusercontent.com/27677180/88386374-ebaecf00-cdb8-11ea-9ddb-0e4801edb093.png">
Replace the current icon for a new one
[Куб.svg.zip](https://github.com/razam-ecosystem/task-tracker/files/4971703/svg.zip)

**Comment by alesiaviktorchyk** [comment]
Implementation is based on new design.
![Screenshot from 2020-07-26 16-57-51](https://user-images.githubusercontent.com/45420854/88480881-38cda500-cf61-11ea-91cf-357a9ebb9465.png)
![Screenshot from 2020-07-26 16-57-59](https://user-images.githubusercontent.com/45420854/88480883-3b2fff00-cf61-11ea-838f-95eada53f687.png)
