### ISSUE TITLE
Correct Sign up page

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#28]
See details: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=1%3A1761
1. Change the colour of the stars (required field) to Accent colour. 
2. Corrext indents; 
3. Correct text size in fileds 15 px for desktop 18 for mobile; 
4. Correct fields size 40px for desktop, 45px for mobile; 
5. Make big check-box 20 px for mobile.

**Comment by alesiaviktorchyk** [comment]
Verified.
