### ISSUE TITLE
Correct Log in page

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#30]
. Correct text in the headline, on the button;
2. Corrext indents; 
3. Correct text size in fileds 15 px for desktop 18 for mobile; 
4. Correct fields size 40px for desktop, 45px for mobile; 
See details: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=1%3A1720

**Comment by alesiaviktorchyk** [comment]
Verified.
