### ISSUE TITLE
Update profile according to design

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#32]
See design details: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=2%3A9657

1. Update indents on filled profile: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=1%3A3027
2. Make field size 45 px for mobile, 40 for desktop, same for buttons. 
3. Update indents of Completed profile page according to the design: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=2%3A9425
4. Remove field "Выборочный участок" from profile

**Comment by alesiaviktorchyk** [comment]
Verified.
