### ISSUE TITLE
Функциональность редактирования профиля.

### ISSUE THREAD

**Issue by Ugzuzg** [razam-ecosystem/task-tracker#4]
https://github.com/razam-ecosystem/task-tracker/issues/6
Верстка страницы профиля

- [x] не отправлять POST запрос для добавления фотографии сразу же после добавления фото
- [x] подгружать картинку предварительно на UI, чтобы юзер мог посмотреть, как это будет выглядеть в круге, а потом уже сохранить изменения
- [x] после сохранения изменений картинка должна быть обновлена, сейчас для того, чтобы увидеть обновленную картинку, нужно перезагрузить страницу.

**Comment by alesiaviktorchyk** [comment]
@Muskos привет, пару пунктов еще:

- [ ] добавить кнопки Скрыть подсказку и Подсказка
- [ ] добавить глаз на пароли, чтобы была возможность посмотреть введенный пароль
- [ ] добавить легенду, расшифровывающую, что значит * ("Поля, обязательные для заполнения*")

- [ ] Проскроливать страницу наверх при нажатии на карандаш редактирования и сохранении изменений. Сейчас страница остается на футере или где-то в середине.
![screenshot-razam jaryk xyz-2020 07](https://user-images.githubusercontent.com/45420854/88455824-617e6d80-ce81-11ea-8dc2-c57de46000a5.gif)

**Comment by alesiaviktorchyk** [comment]
Verified the point above.
