### ISSUE TITLE
Я отправил запрос и друг принял запрос

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#50]
При переходе по ссылке друга у меня будет показываться вот эта страница: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=377%3A1596

Когда друг подтверждает у него будет вот эта: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=550%3A2287

**Comment by alesiaviktorchyk** [comment]
Verified.
