### ISSUE TITLE
Make sure, that buttons style are correct

### ISSUE THREAD

**Issue by 3quetra** [razam-ecosystem/task-tracker#61]
1. Correct buttons' styles: https://www.figma.com/file/h0dR2KwPUCqNoM7NCoXGUP/Razam?node-id=550%3A3164
2. Optional Addition - make buttons shine on click like on the screencast below: 
[Screen Recording 2020-07-26 at 7.02.36 PM.mov.zip](https://github.com/razam-ecosystem/task-tracker/files/4978010/Screen.Recording.2020-07-26.at.7.02.36.PM.mov.zip)

**Comment by alesiaviktorchyk** [comment]
Создать  аккаунт:
![screenshot-razam network-2020 07 30-20_54_00](https://user-images.githubusercontent.com/45420854/88956984-dd741d80-d2a6-11ea-9f81-eada8373cbce.gif)

Отозвать заявку:
![screenshot-razam network-2020 07 30-21_06_35](https://user-images.githubusercontent.com/45420854/88958094-a43cad00-d2a8-11ea-9937-0e130fe3537c.gif)
